Use pip-sync to reflect exactly our requirements.
Travis is shipping: virtualenv==16.1.0 Which causes the follwoing
issue. virtualenv==16.7.7 does not cause the issue, and this is the
one in our requirements-dev.txt, let's use it.

pylint create: /home/mdk/clones/meltygroup/pasee/.tox/pylint
pylint installdeps: -rrequirements-dev.txt
pylint inst: /home/mdk/clones/meltygroup/pasee/.tox/.tmp/package/1/pasee-19.11.3.tar.gz
ERROR: invocation failed (exit code 1), logfile: /home/mdk/clones/meltygroup/pasee/.tox/pylint/log/pylint-2.log
========================================================================== log start ==========================================================================
/home/mdk/clones/meltygroup/pasee/.tox/pylint/lib/python3.8/distutils/__init__.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/mdk/clones/meltygroup/pasee/.tox/pylint/lib/python3.8/site-packages/pip/_vendor/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping
Processing ./.tox/.tmp/package/1/pasee-19.11.3.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
    Complete output from command python setup.py egg_info:
    /home/mdk/clones/meltygroup/pasee/.tox/pylint/lib/python3.8/distutils/__init__.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
      import imp
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/mdk/clones/meltygroup/pasee/.tox/pylint/lib/python3.8/tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-4y6y_uzx/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-4y6y_uzx/
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.